name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: webpro255

      # Step 2: Upload the output
      - name: Upload Snake Animation
        run: |
          mkdir -p dist
          cp .github/contribution-snake.svg dist/snake.svg

      # Step 3: Push the snake.svg to the repository
      - name: Commit and Push Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
