name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Upload the output as an artifact for the contributions calendar
      - name: Upload Snake
        run: |
          mkdir -p dist
          cp .github/contribution-snake.svg dist/snake.svg
      # Push the snake.svg to the profile repository
      - name: Commit and Push Snake
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          path: dist/snake.svg
